name: Build C++ Executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    # Perhatikan nama file output setelah /Fe:
    - name: Compile C++ Code
      run: |
        cl.exe /EHsc nama.cpp /Fe:nama.exe

    # Gunakan nama file yang sama persis di bagian path
    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cpp-program-windows
        path: ${{ github.workspace }}/nama.exe
